version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 231231
      MYSQL_DATABASE: E_commercer
    ports:
      - "3356:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge