version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: api
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysqlPW
      MYSQL_DATABASE: library
    ports:
      - "3357:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: